const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim shirts',
      slug: 'nike-slim-shirts',
      category: 'Shirts',
      image: '/images/p7.jpg', // 679px × 829px
      price: 12,
      countInStock: 15,
      brand: 'Rishabh',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirts',
      slug: 'adidas-fit-shirts',
      category: 'Shirts',
      image: '/images/p6.jpg',
      price: 25,
      countInStock: 200,
      brand: 'Rishabh',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pants',
      slug: 'nike-slim-pants',
      category: 'Pants',
      image: '/images/p8.jpg',
      price: 23,
      countInStock: 15,
      brand: 'Rishabh',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pants',
      slug: 'adidas-fit-pants',
      category: 'Pants',
      image: '/images/p9.jpg',
      price: 45,
      countInStock: 5,
      brand: 'Rishabh',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },{
      name: 'Nike Slim shirts',
      slug: 'nike-slim-shirts',
      category: 'Shirts',
      image: '/images/p10.jpg', // 679px × 829px
      price: 12,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirtsz',
      slug: 'adidas-fit-shirtz',
      category: 'Shirts',
      image: '/images/p11.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidasss',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pantz',
      slug: 'nike-slim-pantz',
      category: 'Pants',
      image: '/images/p12.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nikez',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pantz',
      slug: 'adidas-fit-pantz',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Pumaz',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
